// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Stock.Db.DbModels
{

    // Exchange
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class ExchangeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Exchange>
    {
        public ExchangeConfiguration()
            : this("dbo")
        {
        }

        public ExchangeConfiguration(string schema)
        {
            ToTable("Exchange", schema);
            HasKey(x => x.RowId);

            Property(x => x.RowId).HasColumnName(@"row_id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ExchangeCode).HasColumnName(@"exchange_code").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.ExchangeName).HasColumnName(@"exchange_name").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
        }
    }

}
// </auto-generated>
