// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Stock.Db.DbModels
{

    // PositionShares
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class PositionShareConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PositionShare>
    {
        public PositionShareConfiguration()
            : this("dbo")
        {
        }

        public PositionShareConfiguration(string schema)
        {
            ToTable("PositionShares", schema);
            HasKey(x => x.RowId);

            Property(x => x.RowId).HasColumnName(@"row_id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.HolderId).HasColumnName(@"holder_id").HasColumnType("int").IsOptional();
            Property(x => x.InstrumentId).HasColumnName(@"instrument_id").HasColumnType("int").IsOptional();
            Property(x => x.Amout).HasColumnName(@"amout").HasColumnType("decimal").IsOptional().HasPrecision(14,4);
        }
    }

}
// </auto-generated>
