// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Stock.Db.DbModels
{

    using System.Linq;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class StockDbDbContext : System.Data.Entity.DbContext, IStockDbDbContext
    {
        public System.Data.Entity.DbSet<AssetType> AssetTypes { get; set; } // AssetType
        public System.Data.Entity.DbSet<Exchange> Exchanges { get; set; } // Exchange
        public System.Data.Entity.DbSet<Instrument> Instruments { get; set; } // Instrument
        public System.Data.Entity.DbSet<Party> Parties { get; set; } // Party
        public System.Data.Entity.DbSet<PositionShare> PositionShares { get; set; } // PositionShares

        static StockDbDbContext()
        {
            System.Data.Entity.Database.SetInitializer<StockDbDbContext>(null);
        }

        public StockDbDbContext()
            : base("Name=StockDbConnection")
        {
        }

        public StockDbDbContext(string connectionString)
            : base(connectionString)
        {
        }

        public StockDbDbContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
        }

        public StockDbDbContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
        }

        public StockDbDbContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
        }

        public StockDbDbContext(System.Data.Entity.Core.Objects.ObjectContext objectContext, bool dbContextOwnsObjectContext)
            : base(objectContext, dbContextOwnsObjectContext)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new AssetTypeConfiguration());
            modelBuilder.Configurations.Add(new ExchangeConfiguration());
            modelBuilder.Configurations.Add(new InstrumentConfiguration());
            modelBuilder.Configurations.Add(new PartyConfiguration());
            modelBuilder.Configurations.Add(new PositionShareConfiguration());
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new AssetTypeConfiguration(schema));
            modelBuilder.Configurations.Add(new ExchangeConfiguration(schema));
            modelBuilder.Configurations.Add(new InstrumentConfiguration(schema));
            modelBuilder.Configurations.Add(new PartyConfiguration(schema));
            modelBuilder.Configurations.Add(new PositionShareConfiguration(schema));
            return modelBuilder;
        }
    }
}
// </auto-generated>
